---
name: test_build

on:
  push:
    paths:
      - "**.py"
      - "setup.cfg"
      - "pyproject.toml"
      - "requirements.txt"
      - ".github/workflows/test_build.yaml"
  pull_request:
    paths:
      - "**.py"
      - "setup.cfg"
      - "pyproject.toml"
      - "requirements.txt"
      - ".github/workflows/test_build.yaml"

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install build tools
        run: pip install setuptools wheel build
      - name: Run build
        run: python3 -m build
